//
// Created by Kathleen Nguyen on 11/16/21.
//

#ifndef CATCHASE_STATE_H
#define CATCHASE_STATE_H

enum State
{
    HOVERED, HIDDEN, CLICKED, JUMPED, RAN, FACING_RIGHT, VALID_POSITION, COLLIDED_L, COLLIDED_R, COLLIDED_T, COLLIDED_B,
    MOVE_LEFT, MOVE_RIGHT, MOVE_DOWN, INTERSECTED, ACTIVATED_POWER_UP, TITLE_SCREEN, END_SCREEN,
    LAST
};
#endif //CATCHASE_STATE_H
